name: R-CMD-check

on:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install qpdf
        run: |
          brew update
          brew install qpdf

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.2'

      - name: Install dependencies
        run: Rscript -e 'install.packages("remotes"); remotes::install_deps(dependencies = TRUE)'

      - name: Run R CMD check
        run: R CMD check --no-build-vignettes .
